---
title: "Theory Week 2"
author: "Kieran Healy"
date: "2021-08-25"
output: html_document
---
   

```{r}
### --------------------------------------------------
### Libraries
### --------------------------------------------------
library(tidyverse)
library(here)
library(socviz)
library(patchwork)
library(colorspace)

### --------------------------------------------------
### Fonts: comment out if you don't have these properly installed
library(showtext)
showtext_auto()
library(myriad)
import_myriad_semi()
### --------------------------------------------------

library(gganimate)
library(transformr)

theme_figs <- function(){
  theme_myriad_semi() +
    theme(
      plot.background = element_rect(color = "white"),
      plot.title = element_text(size = rel(2)), 
      axis.title.x = element_text(size = rel(1.8)), 
      axis.title.y = element_text(size = rel(1.8)),
      axis.text.x = element_text(size = rel(1.5)), 
      axis.text.y = element_text(size = rel(1.5)))
}

theme_set(theme_figs())


```


```{r}
### Data
eng_gdp <- read_csv("data/eng_gdp_pop.csv") %>% 
  mutate(group = "1")
```

```{r}

credit <- c("Source: Broadberry et al (2015); Bank of England. Graph: Kieran Healy")

key_yr <- c(1280, 1300, 1345, 1350, 1355, seq(1400, 1650, 50), 
               1685, seq(1700, 2000, 50))

yr_tbl <- tibble(year = key_yr, 
                 yr_lab = as.character(key_yr))

## Very rough periodization
working_df <- eng_gdp %>% 
  left_join(yr_tbl, by = "year") %>% 
  mutate(year = as.integer(year), 
         period = factor(case_when(year < 1345 ~ 1, 
                           year < 1451 ~ 2, 
                           year < 1649 ~ 3, 
                           year < 1686 ~ 4,
                           year < 1751 ~ 5, 
                           year < 1826 ~ 6, 
                           year < 1945 ~ 7, 
                           TRUE ~ 8))) 
```

```{r}

working_df %>% 
  filter(year < 1751) %>% 
  ggplot(mapping = aes(x = pop, 
                       y = gdp/pop, 
                       label = yr_lab,
                       group = group,
                       color = period)) + 
  geom_point(size = 0.9) + 
  geom_path(mapping = aes(label = NULL), size = 1.2) + 
  geom_label(mapping = aes(label = yr_lab)) + 
  scale_x_continuous(labels = scales::label_number_si()) +  
  scale_y_continuous(labels = scales::label_dollar(prefix = "£")) +  
  guides(color = "none") + 
  labs(x = "Population of England", 
       y = "Real GDP per capita", 
       title = "Escaping the Malthusian Trap: I", 
       caption = credit) 

ggsave("figures/malthusian_trap_i.pdf", width = 15, height = 7)
ggsave("figures/malthusian_trap_i.png", width = 15, height = 7, dpi = 200)

working_df %>% 
  ggplot(mapping = aes(x = pop, 
                       y = gdp/pop, 
                       label = yr_lab, 
                       group = group,
                       color = period)) + 
  geom_point(size = 0.9) + 
  geom_path(mapping = aes(label = NULL), size = 1.2) + 
  geom_label(mapping = aes(label = yr_lab)) + 
  scale_x_continuous(labels = scales::label_number_si()) +  
  scale_y_continuous(labels = scales::label_dollar(prefix = "£")) +  
  guides(color = "none") + 
  labs(x = "Population of England", 
       y = "Real GDP per capita", 
       title = "Escaping the Malthusian Trap: II", 
       caption = credit) 

ggsave("figures/malthusian_trap_ii.pdf", width = 15, height = 7)
ggsave("figures/malthusian_trap_ii.png", width = 15, height = 7, dpi = 200)

```

```{r}
### Animation
out_df <- working_df %>% 
  filter(year > 1269) %>% 
  arrange(year)   

## Plot and transition information
out_gg <- out_df %>% 
  ggplot(mapping = aes(x = pop, 
                       y = gdp/pop, 
                       label = yr_lab, 
                       group = group,
                       color = period)) + 
  geom_line(size = 1.2) + 
  geom_point(size = 2) + 
  scale_x_continuous(labels = scales::label_number_si()) +  
  scale_y_continuous(labels = scales::label_dollar(prefix = "£")) +  
  guides(color = "none") + 
  labs(x = "Population of England", 
       y = "Real GDP per capita", 
       title = "Escaping the Malthusian Trap: {frame_along}", 
       caption = credit) + 
  transition_reveal(year) + 
  theme(plot.title = element_text(size = rel(2.5)), 
        plot.caption = element_text(size = rel(1.4)))

## Shares / breakpoints
shares <- out_df %>% 
   mutate(shares = forcats::fct_recode(period, 
                                       "1" = "2", 
                                       "1" = "3")) %>% 
  group_by(shares) %>% 
  summarize(
    max_gdp = max(gdp/pop),
    max_pop = max(pop), 
    n = n()) %>% 
  mutate(pct = n/sum(n))

## Animate  
out_anim <- out_gg +
  view_step_manual(wrap = FALSE,
                   pause_first = TRUE,
                   step_length = c(6, 1, 0.5, 1, 1, 1),
#                  step_length = shares$pct,
                   xmin = c(rep(1.5e6, nrow(shares))),
                   xmax = shares$max_pop,
                   ymin = c(rep(0, nrow(shares))),
                   ymax = shares$max_gdp)


animate(out_anim, fps = 30, 
          duration = 100, width = 1024, height = 768, 
          renderer = av_renderer("figures/malthusian-fin.mp4")) 

```

